ALTER TABLE "Fixture"
  ALTER COLUMN "teamAId" DROP NOT NULL,
  ALTER COLUMN "teamBId" DROP NOT NULL,
  ADD COLUMN "playerAId" TEXT,
  ADD COLUMN "playerBId" TEXT;

ALTER TABLE "Match"
  ALTER COLUMN "homeTeamId" DROP NOT NULL,
  ALTER COLUMN "awayTeamId" DROP NOT NULL,
  ADD COLUMN "playerAId" TEXT,
  ADD COLUMN "playerBId" TEXT;

ALTER TABLE "Fixture" ADD CONSTRAINT "Fixture_playerAId_fkey" FOREIGN KEY ("playerAId") REFERENCES "Player"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Fixture" ADD CONSTRAINT "Fixture_playerBId_fkey" FOREIGN KEY ("playerBId") REFERENCES "Player"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Match" ADD CONSTRAINT "Match_playerAId_fkey" FOREIGN KEY ("playerAId") REFERENCES "Player"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Match" ADD CONSTRAINT "Match_playerBId_fkey" FOREIGN KEY ("playerBId") REFERENCES "Player"("id") ON DELETE CASCADE ON UPDATE CASCADE;