ALTER TABLE "Tournament"
  ADD COLUMN "bannerUrl" TEXT,
  ADD COLUMN "logoUrl" TEXT,
  ADD COLUMN "city" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "ground" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "organizerName" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "organizerPhone" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "organizerEmail" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "type" TEXT NOT NULL DEFAULT 'OPEN',
  ADD COLUMN "matchCategories" JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN "shuttleType" TEXT NOT NULL DEFAULT 'PLASTIC',
  ADD COLUMN "bestOf" INTEGER NOT NULL DEFAULT 3;

ALTER TABLE "Fixture"
  ADD COLUMN "bestOf" INTEGER NOT NULL DEFAULT 3;